### ISSUE TITLE
Recommend EnforceHostMiddleware after SecurityMiddleware

### ISSUE THREAD

**Issue by davidfischer** [dabapps/django-enforce-host#3]
Firstly, thanks for this middleware. This was exactly what I was looking for.

One small tweak I changed from the recommended setting in the README was to put the `EnforceHostMiddleware` after  `SecurityMiddleware`. The advantage of this is pretty minor but it allows for following [Mozilla's recommendations for redirects](https://infosec.mozilla.org/guidelines/web_security#http-redirections). Specifically from the Mozilla docs: 

    Sites that listen on port 80 should only redirect to the same resource on HTTPS

By letting Django's `SecurityMiddleware` come first, it will handle the HTTP -> HTTPS redirection to the same host (assuming [`SECURE_SSL_REDIRECT=True`](https://docs.djangoproject.com/en/2.2/ref/settings/#secure-ssl-redirect) and `SECURE_SSL_HOST=None`). Then the `EnforceHostMiddleware` will redirect to the preferred host.

If you agree, I can send a PR updating the README.

**Comment by j4mie** [comment]
@davidfischer huge apologies, two years later and I've just seen this issue! I think that would be an excellent PR, but I totally understand if you've moved on and no longer have time or motivation.
